### ISSUE TITLE
Fix Undefined Token ID

### ISSUE THREAD

**Issue by joshuanianji** [RubberNoodles/joke-with-friends#7]
`res.data.tokenId` in `login.tsx` returns undefined and does not work when a user logs in

**Comment by RubberNoodles** [comment]
It was coded as res.data.tokenId but the actual name for it was res.data.userIdToken. I was tipped off that this was the issue because console logging res.data.tokenId was `undefined`.

**Comment by RubberNoodles** [comment]
Haha that was a bit annoying :')
